/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modeloConnection.ConexaoDB;

/**
 *
 * @author Vini Lopes
 * Arquivo alterado diretamente no repositório.
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoDB conecta = new ConexaoDB();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastros = new javax.swing.JLabel();
        jButtonCadAlbuns = new javax.swing.JButton();
        jButtonCadArtistas = new javax.swing.JButton();
        jButtonCadFaixas = new javax.swing.JButton();
        jButtonCadGeneros = new javax.swing.JButton();
        jButtonCadGravadoras = new javax.swing.JButton();
        jLabelRelatorios = new javax.swing.JLabel();
        jButtonRelatorios = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemAlbuns = new javax.swing.JMenuItem();
        jMenuItemArtistas = new javax.swing.JMenuItem();
        jMenuItemFaixas = new javax.swing.JMenuItem();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jMenuItemGravadoras = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatorios = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Musical Database");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadastros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadastros.setText("   CADASTROS");
        getContentPane().add(jLabelCadastros, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 5, 137, 30));

        jButtonCadAlbuns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_albuns.png"))); // NOI18N
        jButtonCadAlbuns.setToolTipText("Álbuns");
        jButtonCadAlbuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAlbunsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadAlbuns, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 137, -1));

        jButtonCadArtistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_artista.png"))); // NOI18N
        jButtonCadArtistas.setToolTipText("Artistas");
        jButtonCadArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadArtistasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 137, -1));

        jButtonCadFaixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_faixas.png"))); // NOI18N
        jButtonCadFaixas.setToolTipText("Faixas");
        jButtonCadFaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadFaixasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadFaixas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 137, -1));

        jButtonCadGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_generos.png"))); // NOI18N
        jButtonCadGeneros.setToolTipText("Gêneros");
        jButtonCadGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadGenerosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 137, -1));

        jButtonCadGravadoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_gravadora.png"))); // NOI18N
        jButtonCadGravadoras.setToolTipText("Gravadoras");
        jButtonCadGravadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadGravadorasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadGravadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 137, -1));

        jLabelRelatorios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRelatorios.setText("  RELATÓRIOS");
        getContentPane().add(jLabelRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 345, 140, 30));

        jButtonRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_relatorios.png"))); // NOI18N
        jButtonRelatorios.setToolTipText("Relatórios");
        jButtonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 137, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_internalframe.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 540));

        jMenuCadastros.setText("Cadastros");

        jMenuItemAlbuns.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAlbuns.setText("Álbuns");
        jMenuItemAlbuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlbunsActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemAlbuns);

        jMenuItemArtistas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemArtistas.setText("Artistas");
        jMenuItemArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArtistasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemArtistas);

        jMenuItemFaixas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFaixas.setText("Faixas");
        jMenuItemFaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFaixasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFaixas);

        jMenuItemGeneros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGeneros.setText("Gêneros");
        jMenuItemGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemGeneros);

        jMenuItemGravadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGravadoras.setText("Gravadoras");
        jMenuItemGravadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGravadorasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemGravadoras);

        jMenuBarTelaPrincipal.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelatorios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRelatorios.setText("Tela de Relatórios");
        jMenuItemRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatoriosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelatorios);

        jMenuBarTelaPrincipal.add(jMenuRelatorios);

        jMenuSair.setText("Sair");

        jMenuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFechar.setText("Fechar Aplicação");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemFechar);

        jMenuBarTelaPrincipal.add(jMenuSair);

        setJMenuBar(jMenuBarTelaPrincipal);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlbunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlbunsActionPerformed
        FormAlbuns tela = new FormAlbuns();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlbunsActionPerformed

    private void jMenuItemFaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFaixasActionPerformed
        FormFaixas tela = new FormFaixas();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemFaixasActionPerformed

    private void jMenuItemArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArtistasActionPerformed
        FormArtistas tela = new FormArtistas();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemArtistasActionPerformed

    private void jMenuItemGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerosActionPerformed
        FormGeneros tela = new FormGeneros();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemGenerosActionPerformed

    private void jMenuItemGravadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGravadorasActionPerformed
        FormGravadora tela = new FormGravadora();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemGravadorasActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        //conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jButtonCadGravadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadGravadorasActionPerformed
        FormGravadora tela = new FormGravadora();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadGravadorasActionPerformed

    private void jButtonCadAlbunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAlbunsActionPerformed
        FormAlbuns tela = new FormAlbuns();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadAlbunsActionPerformed

    private void jButtonCadArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadArtistasActionPerformed
        FormArtistas tela = new FormArtistas();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadArtistasActionPerformed

    private void jButtonCadFaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFaixasActionPerformed
        FormFaixas tela = new FormFaixas();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadFaixasActionPerformed

    private void jButtonCadGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadGenerosActionPerformed
        FormGeneros tela = new FormGeneros();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadGenerosActionPerformed

    private void jButtonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatoriosActionPerformed
        FormRelatorios tela = new FormRelatorios();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonRelatoriosActionPerformed

    private void jMenuItemRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatoriosActionPerformed
        FormRelatorios tela = new FormRelatorios();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadAlbuns;
    private javax.swing.JButton jButtonCadArtistas;
    private javax.swing.JButton jButtonCadFaixas;
    private javax.swing.JButton jButtonCadGeneros;
    private javax.swing.JButton jButtonCadGravadoras;
    private javax.swing.JButton jButtonRelatorios;
    private javax.swing.JLabel jLabelCadastros;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelRelatorios;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemAlbuns;
    private javax.swing.JMenuItem jMenuItemArtistas;
    private javax.swing.JMenuItem jMenuItemFaixas;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemGravadoras;
    private javax.swing.JMenuItem jMenuItemRelatorios;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
